### ISSUE TITLE
Root element prefix

### ISSUE THREAD

**Issue by WhiteApfel** [tefra/xsdata#542] opened 2021-06-25 14:21 UTC
XML:
```xml
<smz:GetGrantedPermissionsRequest xmlns:smz="urn://x-artefacts-gnivc-ru/ais3/SMZ/SmzPartnersIntegrationService/types/1.0">
  <smz:Inn>302502032671</smz:Inn>
</smz:GetGrantedPermissionsRequest>
```

Leaving 'smz'-prefix at the root element results in a ParserError:
`xsdata.exceptions.ParserError: No class found matching root: {urn://x-artefacts-gnivc-ru/ais3/SMZ/SmzPartnersIntegrationService/types/1.0}GetGrantedPermissionsRequest`

If removed, then everything will work correctly, but then it will be invalid according to the XML schema

**Comment by tefra** [comment] 2021-06-25 21:05
Hi @WhiteApfel can your share the xml schema?

**Comment by WhiteApfel** [comment] 2021-06-25 21:11
[smz-partners-merged-scheme-v0.28.tar.gz](https://github.com/tefra/xsdata/files/6718838/smz-partners-merged-scheme-v0.28.tar.gz)

**Comment by tefra** [comment] 2021-06-25 21:26
I can't reproduce it, please provide a code sample as well.

```console
❯ xsdata issue/schema/smz-partners-merged-scheme-v0.28.xsd --package issue.models.generated
Parsing schema smz-partners-merged-scheme-v0.28.xsd
Compiling schema smz-partners-merged-scheme-v0.28.xsd
Builder: 138 main and 12 inner classes
Analyzer input: 138 main and 12 inner classes
Analyzer output: 140 main and 10 inner classes
Generating package: init
Generating package: issue.models.generated.smz_partners_merged_scheme_v0_28
```

```python
from issue.models.generated import GetGrantedPermissionsRequest
from xsdata.formats.dataclass.parsers import XmlParser

xml = """<smz:GetGrantedPermissionsRequest xmlns:smz="urn://x-artefacts-gnivc-ru/ais3/SMZ/SmzPartnersIntegrationService/types/1.0">
  <smz:Inn>302502032671</smz:Inn>
</smz:GetGrantedPermissionsRequest>"""

parser = XmlParser()
print(parser.from_string(xml, GetGrantedPermissionsRequest))
```

```
GetGrantedPermissionsRequest(inn='302502032671')
```

If you are not providing the target type in the parser endpoint, please make sure the class is already imported otherwise there is no way to auto locate the class.

**Comment by WhiteApfel** [comment] 2021-06-25 21:36
I didn't specify the target class. And running this code got an error.

```python
from faina_semenovna.models.smz_v0_28 import GetGrantedPermissionsRequest
from xsdata.formats.dataclass.parsers import XmlParser

xml = """<smz:GetGrantedPermissionsRequest xmlns:smz="urn://x-artefacts-gnivc-ru/ais3/SMZ/SmzPartnersIntegrationService/types/1.0">
  <smz:Inn>302502032671</smz:Inn>
</smz:GetGrantedPermissionsRequest>"""

parser = XmlParser()
print(parser.from_string(xml))
```

Error:
```
Traceback (most recent call last):
  File "/home/white/.local/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/nodes.py", line 495, in start
    item = queue[-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/white/.local/lib/python3.9/site-packages/xsdata/formats/bindings.py", line 25, in from_string
    return self.from_bytes(source.encode(), clazz)
  File "/home/white/.local/lib/python3.9/site-packages/xsdata/formats/bindings.py", line 29, in from_bytes
    return self.parse(io.BytesIO(source), clazz)
  File "/home/white/.local/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/nodes.py", line 464, in parse
    result = handler.parse(source)
  File "/home/white/.local/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/handlers/lxml.py", line 39, in parse
    return self.process_context(ctx)
  File "/home/white/.local/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/handlers/lxml.py", line 45, in process_context
    self.parser.start(
  File "/home/white/.local/lib/python3.9/site-packages/xsdata/formats/dataclass/parsers/nodes.py", line 510, in start
    raise ParserError(f"No class found matching root: {qname}")
xsdata.exceptions.ParserError: No class found matching root: {urn://x-artefacts-gnivc-ru/ais3/SMZ/SmzPartnersIntegrationService/types/1.0}GetGrantedPermissionsRequest
```

If I specify the target class, as in your example, then it works fine. The problem is precisely in the prefix

**Comment by tefra** [comment] 2021-06-25 21:50
How did you generate the models @WhiteApfel? Can you provide the command as well?

I tried mimicking your package but it still works for me
`xsdata issue/schema/smz-partners-merged-scheme-v0.28.xsd --package issue.models.smz_v0_28 --structure-style single-package
`

**Comment by tefra** [comment] 2021-06-25 21:56
On top of your package you see the module `__NAMESPACE__` like this?

```python
from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from typing import List, Optional
from xsdata.models.datatype import XmlDate, XmlDateTime

__NAMESPACE__ = "urn://x-artefacts-gnivc-ru/ais3/SMZ/SmzPartnersIntegrationService/types/1.0"


@dataclass
class AttachedFile:
```

**Comment by WhiteApfel** [comment] 2021-06-25 22:01
Oh, I really have a problem on this line. Apparently, I accidentally inserted something there with the middle mouse button. I apologize for your time.

**Comment by tefra** [comment] 2021-06-25 22:05
No problem @WhiteApfel glad we sorted this out

**Closed by tefra** 2021-06-25 22:05 UTC
