### ISSUE TITLE
UnitTests failing with latest 21.1 version

### ISSUE THREAD

**Issue by eLvErDe** [tefra/xsdata#378] opened 2021-01-10 09:57 UTC
```
=================================== FAILURES ===================================
_______________________ GeneratorConfigTests.test_create _______________________

self = <tests.models.test_config.GeneratorConfigTests testMethod=test_create>

    def test_create(self):
        file_path = Path(tempfile.mktemp())
        version = get_distribution("xsdata").version
        obj = GeneratorConfig.create()
        with file_path.open("w") as fp:
            obj.write(fp, obj)
    
        expected = (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<Config xmlns="http://pypi.org/project/xsdata" version="{version}">\n'
            '  <Output wsdl="false" maxLineLength="79">\n'
            "    <Package>generated</Package>\n"
            "    <Format>pydata</Format>\n"
            "    <Structure>filenames</Structure>\n"
            "    <DocstringStyle>reStructuredText</DocstringStyle>\n"
            "    <CompoundFields>false</CompoundFields>\n"
            "  </Output>\n"
            "  <Conventions>\n"
            '    <ClassName case="pascalCase" safePrefix="type"/>\n'
            '    <FieldName case="snakeCase" safePrefix="value"/>\n'
            '    <ModuleName case="snakeCase" safePrefix="mod"/>\n'
            '    <PackageName case="snakeCase" safePrefix="pkg"/>\n'
            "  </Conventions>\n"
            "  <Aliases>\n"
            '    <ClassName source="fooType" target="Foo"/>\n'
            '    <ClassName source="ABCSomething" target="ABCSomething"/>\n'
            '    <FieldName source="ChangeofGauge" target="change_of_gauge"/>\n'
            '    <PackageName source="http://www.w3.org/1999/xhtml" target="xtml"/>\n'
            '    <ModuleName source="2010.1" target="2020a"/>\n'
            "  </Aliases>\n"
            "</Config>\n"
        )
>       self.assertEqual(expected, file_path.read_text())
E       AssertionError: '<?xm[105 chars]tput wsdl="false" maxLineLength="79">\n    <Pa[788 chars]g>\n' != '<?xm[105 chars]tput maxLineLength="79" wsdl="false">\n    <Pa[788 chars]g>\n'
E       Diff is 1016 characters long. Set self.maxDiff to None to see it.

tests/models/test_config.py:43: AssertionError
________________________ GeneratorConfigTests.test_read ________________________

self = <tests.models.test_config.GeneratorConfigTests testMethod=test_read>

    def test_read(self):
        existing = (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            '<Config xmlns="http://pypi.org/project/xsdata" version="20.8">\n'
            '  <Output wsdl="false" maxLineLength="79">\n'
            "    <Package>foo.bar</Package>\n"
            "  </Output>\n"
            "  <Conventions>\n"
            '    <ClassName case="pascalCase" safePrefix="type"/>\n'
            "  </Conventions>\n"
            "  <Aliases/>\n"
            "</Config>\n"
        )
        version = get_distribution("xsdata").version
        file_path = Path(tempfile.mktemp())
        file_path.write_text(existing, encoding="utf-8")
        config = GeneratorConfig.read(file_path)
        with file_path.open("w") as fp:
            GeneratorConfig.write(fp, config)
    
        expected = (
            '<?xml version="1.0" encoding="UTF-8"?>\n'
            f'<Config xmlns="http://pypi.org/project/xsdata" version="{version}">\n'
            '  <Output wsdl="false" maxLineLength="79">\n'
            "    <Package>foo.bar</Package>\n"
            "    <Format>pydata</Format>\n"
            "    <Structure>filenames</Structure>\n"
            "    <DocstringStyle>reStructuredText</DocstringStyle>\n"
            "    <CompoundFields>false</CompoundFields>\n"
            "  </Output>\n"
            "  <Conventions>\n"
            '    <ClassName case="pascalCase" safePrefix="type"/>\n'
            '    <FieldName case="snakeCase" safePrefix="value"/>\n'
            '    <ModuleName case="snakeCase" safePrefix="mod"/>\n'
            '    <PackageName case="snakeCase" safePrefix="pkg"/>\n'
            "  </Conventions>\n"
            "  <Aliases/>\n"
            "</Config>\n"
        )
>       self.assertEqual(expected, file_path.read_text())
E       AssertionError: '<?xm[105 chars]tput wsdl="false" maxLineLength="79">\n    <Pa[475 chars]g>\n' != '<?xm[105 chars]tput maxLineLength="79" wsdl="false">\n    <Pa[475 chars]g>\n'
E       Diff is 697 characters long. Set self.maxDiff to None to see it.

tests/models/test_config.py:85: AssertionError
```

**Comment by tefra** [comment] 2021-01-10 10:24
The ci is running on 6 python versions and 3 operating systems (mac, windows, ubuntu) and I can't reproduce it, can you share more info about your env and how you run the test suite.

**Comment by eLvErDe** [comment] 2021-01-10 10:27
Sure ;-)

Can you use a docker image ?

**Comment by tefra** [comment] 2021-01-10 10:27
yeah

**Comment by eLvErDe** [comment] 2021-01-10 11:48
So here we go.

Dockerfile:

```
FROM debian:buster

RUN apt update && apt --yes install wget python3-pytest python3-pytest-benchmark --no-install-recommends

RUN mkdir pkgs \
  && cd pkgs \
  && wget http://dedibox.le-vert.net/pub/xsdata-pkgs/python3-click-default-group_1.2.2-1_all.deb \
  && wget http://dedibox.le-vert.net/pub/xsdata-pkgs/python3-docformatter_1.4-1_all.deb \
  && wget http://dedibox.le-vert.net/pub/xsdata-pkgs/python3-untokenize_0.1.1-1_all.deb \
  && wget http://dedibox.le-vert.net/pub/xsdata-pkgs/python3-xsdata_21.1+dfsg-1_all.deb \
  && apt install ./python3-click-default-group_1.2.2-1_all.deb \
                 ./python3-docformatter_1.4-1_all.deb \
                 ./python3-untokenize_0.1.1-1_all.deb \
                 ./python3-xsdata_21.1+dfsg-1_all.deb \
                 --yes --no-install-recommends
```

Build and get a shell inside the image

```
docker build . -t test-xsdata

docker run -it test-xsdata /bin/bash
```

Run the test inside the container:

``` 
wget --no-check-certificate https://github.com/tefra/xsdata/archive/v21.1.tar.gz
tar xf v21.1.tar.gz 
cd xsdata-21.1/
python3 -m pytest
```

**Comment by tefra** [comment] 2021-01-10 13:32
```diff
E       -   <Output wsdl="false" maxLineLength="79">
E       +   <Output maxLineLength="79" wsdl="false">
```

Interesting stuff, xsdata is pretty flexible with dependencies it doesn't enforce minimum versions for two reasons
1. Most of the features I use are very basic and exist in these libraries since forever.
2. I believe a library such as xsdata shouldn't enforce versions that might affect parent projects.

In your setup you endup with lxml=='4.3.2', it was a known issue that was fixed in [4.4](https://github.com/lxml/lxml/blob/master/CHANGES.txt) (2019-07), that's even before I started xsdata.

This is the second time it has occurred for you, the first time was with jinja right? I am gonna cook the test to pass anyway and start thinking if I might want to break my rules with min versions.

**Comment by eLvErDe** [comment] 2021-01-10 13:35
It is indeed the second time, the reason is that I'm using your package on a Debian stable system, I tend to avoid going full-pip for obvious easy of distribution of my softwares so yes, it's running with dependencies available in Debian stable (release a couple of years ago)

**Comment by tefra** [comment] 2021-01-10 13:44
Maybe I am too stubborn, anyway the patch for tests to pass is on master and I promise I will think about it.

**Closed by tefra** 2021-01-10 13:44 UTC

**Comment by eLvErDe** [comment] 2021-01-10 13:46
Thanks
